# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Shotgun Desktop when it
# is running in its project level configuration

includes:
- ../app_launchers.yml
- ../common/engines.yml
- ../common/apps.yml

desktop.project:
  apps:
    tk-multi-launchmari: '@launch_mari'
    tk-multi-launchmotionbuilder: '@launch_motionbuilder'
    tk-multi-launchsoftimage: '@launch_softimage'
    tk-multi-screeningroom: '@launch_screeningroom'
    tk-multi-launchapp:
      use_software_entity: true
      location: "@common.apps.tk-multi-launchapp.location"
  groups:
  - matches: ['*Houdini*', '*Mari*', '*Max*', '*Maya*', '*Motion*', '*Nuke*', '*Photoshop*', '*Softimage*']
    name: Creative Tools
  - matches: ['*Hiero*']
    name: Editorial Tools
  - matches: ['*Fla*']
    name: Finishing Tools
  location: "@common.engines.tk-desktop.location"
