# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Shotgun Desktop when it
# is running in its project level configuration

includes:
- ../common/frameworks.yml
- ../common/engines.yml
- ../common/apps.yml
- ../app_launchers.yml

desktop.project:
  apps:

    # context menu commands
    tk-multi-pythonconsole: '@common.apps.tk-multi-pythonconsole'
    tk-multi-screeningroom: '@launch_screeningroom'

    # stand alone publisher
    tk-multi-publish2: "@common.apps.tk-multi-publish2"

    # App launchers

    # handles auto-discovery for configured Software entities
    tk-multi-launchapp: '@common.apps.launchapp-software'

    # Engines that do not support the Software entity auto-discovery
    #tk-multi-launchhiero: '@launch_hiero'
    #tk-multi-launchmari: '@launch_mari'
    #tk-multi-launchmotionbuilder: '@launch_motionbuilder'
    #tk-multi-launchsoftimage: '@launch_softimage'

  collapse_rules:
  - {button_label: $app, match: Launch $app, menu_label: None}
  default_group: Studio
  groups:
  - matches:
    - '*Houdini*'
    - '*Mari*'
    - '*Max*'
    - '*Maya*'
    - '*Motion*'
    - '*Nuke*'
    - '*Photoshop*'
    - 'CC*'
    - '*Softimage*'
    name: Creative Tools
  - matches:
    - '*Hiero*'
    name: Editorial Tools
  - matches:
    - '*Fla*'
    name: Finishing Tools
  location: "@common.engines.tk-desktop.location"
