# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Shotgun Desktop when it
# is running in its project level configuration

includes:
- ../common/app_locations.yml
- ../common/engine_locations.yml
- ../common/settings/tk-multi-launchapp.yml
- ../common/settings/tk-multi-publish2.yml
- ../common/settings/tk-multi-screeningroom.yml

desktop.project:
  apps:

    # python console
    tk-multi-pythonconsole:
      location: "@common.apps.tk-multi-pythonconsole.location"

    # stand alone publisher
    tk-multi-publish2:
        help_url: "@common.settings.tk-multi-publish2.help_url"
        location: "@common.apps.tk-multi-publish2.location"

    # launchers for engines without Software entity/startup support
    tk-multi-launchhiero: "@common.settings.tk-multi-launchapp.hiero"
    tk-multi-launchmari: "@common.settings.tk-multi-launchapp.mari"
    tk-multi-launchmotionbuilder: "@common.settings.tk-multi-launchapp.motionbuilder"
    tk-multi-launchsoftimage: "@common.settings.tk-multi-launchapp.softimage"

    # auto-discover Software using eneityt/startup logic
    tk-multi-launchapp: "@common.settings.tk-multi-launchapp"

    tk-multi-screeningroom: "@common.settings.tk-multi-screeningroom.rv"

  groups:
  - matches:
    - "*Houdini*"
    - "*Mari*"
    - "*Max*"
    - "*Maya*"
    - "*Motion*"
    - "*Nuke*"
    - "*Photoshop*"
    - "*Softimage*"
    name: Creative Tools
  - matches:
    - "*Hiero*"
    name: Editorial Tools
  - matches:
    - "*Fla*"
    name: Finishing Tools
  location: "@common.engines.tk-desktop.location"
