# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# this configuration defines the behavior of the Hiero Integration when it
# is running in its project level configuration

includes:
- ../common/apps.yml
- ../common/engines.yml
- ../common/apps.yml

hiero.project:
  apps:
    tk-hiero-export:
      location:
        version: v0.4.1
        type: app_store
        name: tk-hiero-export
      nuke_script_toolkit_write_nodes:
      - {channel: stereoexr32, name: 'Stereo Exr, 32 bit'}
      - {channel: stereoexr16, name: 'Stereo Exr, 16 bit'}
      - {channel: monodpx, name: Mono Dpx}
      template_nuke_script_path: nuke_shot_work
      template_plate_path: hiero_plate_path
      template_render_path: hiero_render_path
      template_version: hiero_version
    tk-hiero-openinshotgun:
      location:
        version: v0.3.3
        type: app_store
        name: tk-hiero-openinshotgun
    tk-multi-about: '@common.apps.tk-multi-about'
    tk-multi-shotgunpanel: '@common.apps.tk-multi-shotgunpanel'
    tk-multi-publish:
      allow_taskless_publishes: true
      display_name: Publish Project
      expand_single_items: false
      hook_copy_file: default
      hook_post_publish: default
      hook_primary_pre_publish: default
      hook_primary_publish: default
      hook_scan_scene: default
      hook_secondary_pre_publish: default
      hook_secondary_publish: default
      hook_thumbnail: default
      location:
        version: v0.10.0
        type: app_store
        name: tk-multi-publish
      primary_description: Publish and version up the selected Hiero project
      primary_display_name: Hiero Publish
      primary_icon: icons/publish_hiero_main.png
      primary_publish_template: hiero_project_publish
      primary_scene_item_type: work_file
      primary_tank_type: Hiero Project
      secondary_outputs: []
      template_work: hiero_project_work
    tk-multi-snapshot:
      location:
        version: v0.7.3
        type: app_store
        name: tk-multi-snapshot
      template_snapshot: hiero_project_snapshot
      template_work: hiero_project_work
    tk-multi-workfiles2:
      allow_task_creation: true
      create_new_task_hook: default
      custom_actions_hook: default
      entities:
      - caption: Projects
        entity_type: Project
        filters: []
        hierarchy: [name]
      file_extensions: []
      hook_copy_file: default
      hook_filter_publishes: default
      hook_filter_work_files: default
      hook_scene_operation: default
      launch_at_startup: false
      location: '@common.apps.workfiles2.location'
      my_tasks_extra_display_fields: []
      saveas_default_name: scene
      saveas_prefer_version_up: false
      show_my_tasks: false
      template_publish: hiero_project_publish
      template_publish_area: hiero_project_publish_area
      template_work: hiero_project_work
      template_work_area: hiero_project_work_area
      version_compare_ignore_fields: []
  bin_context_menu:
  - {app_instance: tk-multi-workfiles2, keep_in_menu: false, name: File Save...,
    requires_selection: true}
  - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot..., requires_selection: true}
  - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot History...,
    requires_selection: true}
  - {app_instance: tk-multi-publish, keep_in_menu: false, name: Publish Project...,
    requires_selection: true}
  location: '@common.engines.tk-nuke.location'
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  spreadsheet_context_menu:
  - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
    requires_selection: true}
  timeline_context_menu:
  - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
    requires_selection: true}
