# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################

includes:
- ./includes/common/frameworks.yml
- ./includes/desktop/project.yml
- ./includes/flame/project.yml
- ./includes/houdini/project.yml
- ./includes/maya/project.yml
- ./includes/nuke/project.yml
- ./includes/photoshopcc/project.yml
- ./includes/shell/project.yml
- ./includes/shotgun/project.yml
- ./includes/3dsmax/project.yml

- ./includes/hiero/project.yml
- ./includes/mari/project.yml
- ./includes/motionbuilder/project.yml
- ./includes/nukestudio/project.yml
- ./includes/softimage/project.yml

#################################################################################################
# define all the items that should appear in this environment



engines:
  #
  # -------------------------------------------------
  # 3dsmax plus
  # -------------------------------------------------
  tk-3dsmaxplus: '@3dsmax.project'
  #
  # -------------------------------------------------
  # Shotgun Desktop
  # -------------------------------------------------
  tk-desktop: '@desktop.project'
  #
  # -------------------------------------------------
  # Hiero
  # -------------------------------------------------
  tk-hiero: '@hiero.project'
  #
  # -------------------------------------------------
  # Houdini
  # -------------------------------------------------
  tk-houdini: '@houdini.project'
  #
  # -------------------------------------------------
  # Mari
  # -------------------------------------------------
  tk-mari: '@mari.project'
  #
  # -------------------------------------------------
  # Maya
  # -------------------------------------------------
  tk-maya: '@maya.project'
  #
  # -------------------------------------------------
  # Motionbuilder
  # -------------------------------------------------
  tk-motionbuilder: '@motionbuilder.project'
  #
  # -------------------------------------------------
  # Nuke
  # -------------------------------------------------
  tk-nuke: '@nuke.project'
  #
  # -------------------------------------------------
  # Nuke Studio
  # -------------------------------------------------
  tk-nukestudio: '@nukestudio.project'
  #
  # -------------------------------------------------
  # Photoshop CC
  # -------------------------------------------------
  tk-photoshopcc: '@photoshopcc.project'
  #
  # -------------------------------------------------
  # Flame
  # -------------------------------------------------
  tk-flame: '@flame.project'
  #
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell: '@shell.project'
  #
  # -------------------------------------------------
  # Shotgun
  # -------------------------------------------------
  tk-shotgun: '@shotgun.project'
  #
  # -------------------------------------------------
  # Softimage
  # -------------------------------------------------
  tk-softimage: '@softimage.project'

