# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml

#################################################################################################
# define all the items that should appear in this environment



engines:
  #
  # -------------------------------------------------
  # 3dsmax plus
  # -------------------------------------------------
  tk-3dsmaxplus:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v0.2.0
      type: app_store
      name: tk-3dsmaxplus
  #
  # -------------------------------------------------
  # Shotgun Desktop
  # -------------------------------------------------
  tk-desktop:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchhiero: '@launch_hiero'
      tk-multi-launchhoudini: '@launch_houdini'
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchnukestudio: '@launch_nukestudio'
      tk-multi-launchphotoshopcc: '@launch_photoshopcc'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
    groups:
    - matches: ['*Houdini*', '*Mari*', '*Max*', '*Maya*', '*Motion*', '*Nuke*', '*Photoshop*',
        '*Softimage*']
      name: Creative Tools
    - matches: ['*Hiero*']
      name: Editorial Tools
    - matches: ['*Fla*']
      name: Finishing Tools
    location:
      version: v2.0.23
      type: app_store
      name: tk-desktop
  #
  # -------------------------------------------------
  # Hiero
  # -------------------------------------------------
  tk-hiero:
    apps:
      tk-hiero-export:
        location:
          version: v0.3.32
          type: app_store
          name: tk-hiero-export
        nuke_script_toolkit_write_nodes:
        - {channel: stereoexr32, name: 'Stereo Exr, 32 bit'}
        - {channel: stereoexr16, name: 'Stereo Exr, 16 bit'}
        - {channel: monodpx, name: Mono Dpx}
        template_nuke_script_path: nuke_shot_work
        template_plate_path: hiero_plate_path
        template_render_path: hiero_render_path
        template_version: hiero_version
      tk-hiero-openinshotgun:
        location:
          version: v0.3.3
          type: app_store
          name: tk-hiero-openinshotgun
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-publish:
        display_name: Publish Project
        location:
          version: v0.10.0
          type: app_store
          name: tk-multi-publish
        primary_description: Publish and version up the selected Hiero project
        primary_display_name: Hiero Publish
        primary_icon: icons/publish_hiero_main.png
        primary_publish_template: hiero_project_publish
        primary_tank_type: Hiero Project
        template_work: hiero_project_work
      tk-multi-snapshot:
        location:
          version: v0.7.0
          type: app_store
          name: tk-multi-snapshot
        template_snapshot: hiero_project_snapshot
        template_work: hiero_project_work
      tk-multi-workfiles2:
        location:
          version: v0.9.0
          type: app_store
          name: tk-multi-workfiles2
        template_publish: hiero_project_publish
        template_publish_area: hiero_project_publish_area
        template_work: hiero_project_work
        template_work_area: hiero_project_work_area
    bin_context_menu:
    - {app_instance: tk-multi-workfiles2, keep_in_menu: false, name: File Save...,
      requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot History...,
      requires_selection: true}
    - {app_instance: tk-multi-publish, keep_in_menu: false, name: Publish Project...,
      requires_selection: true}
    location:
      version: v0.6.11
      type: app_store
      name: tk-nuke
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    spreadsheet_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
    timeline_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
  #
  # -------------------------------------------------
  # Houdini
  # -------------------------------------------------
  tk-houdini:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v1.0.10
      type: app_store
      name: tk-houdini
  #
  # -------------------------------------------------
  # Mari
  # -------------------------------------------------
  tk-mari:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-workfiles:
        location:
          version: v0.7.4
          type: app_store
          name: tk-multi-workfiles
        sg_entity_types: [Asset]
    location:
      version: v1.1.4
      type: app_store
      name: tk-mari
  #
  # -------------------------------------------------
  # Maya
  # -------------------------------------------------
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2-launch-at-startup'
    location:
      version: v0.7.14
      type: app_store
      name: tk-maya
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
  #
  # -------------------------------------------------
  # Motionbuilder
  # -------------------------------------------------
  tk-motionbuilder:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v0.3.1
      type: app_store
      name: tk-motionbuilder
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
  #
  # -------------------------------------------------
  # Nuke
  # -------------------------------------------------
  tk-nuke:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v0.6.11
      type: app_store
      name: tk-nuke
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
  #
  # -------------------------------------------------
  # Nuke Studio
  # -------------------------------------------------
  tk-nukestudio:
    apps:
      tk-hiero-export:
        location:
          version: v0.3.32
          type: app_store
          name: tk-hiero-export
        nuke_script_toolkit_write_nodes:
        - {channel: stereoexr32, name: 'Stereo Exr, 32 bit'}
        - {channel: stereoexr16, name: 'Stereo Exr, 16 bit'}
        - {channel: monodpx, name: Mono Dpx}
        template_nuke_script_path: nuke_shot_work
        template_plate_path: hiero_plate_path
        template_render_path: hiero_render_path
        template_version: hiero_version
      tk-hiero-openinshotgun:
        location:
          version: v0.3.3
          type: app_store
          name: tk-hiero-openinshotgun
      tk-multi-about: '@about'
      tk-multi-publish:
        display_name: Publish Project
        location:
          version: v0.10.0
          type: app_store
          name: tk-multi-publish
        primary_description: Publish and version up the selected Hiero project
        primary_display_name: Hiero Publish
        primary_icon: icons/publish_hiero_main.png
        primary_publish_template: hiero_project_publish
        primary_tank_type: Hiero Project
        template_work: hiero_project_work
      tk-multi-snapshot:
        location:
          version: v0.7.0
          type: app_store
          name: tk-multi-snapshot
        template_snapshot: hiero_project_snapshot
        template_work: hiero_project_work
      tk-multi-workfiles2:
        entities:
        - caption: Projects
          entity_type: Project
          filters: []
          hierarchy: [name]
        location:
          version: v0.9.0
          type: app_store
          name: tk-multi-workfiles2
        show_my_tasks: false
        template_publish: hiero_project_publish
        template_publish_area: hiero_project_publish_area
        template_work: hiero_project_work
        template_work_area: hiero_project_work_area
      tk-multi-shotgunpanel:
        location:
          version: v1.3.0
          type: app_store
          name: tk-multi-shotgunpanel
        action_mappings:
          PublishedFile:
          - actions:
            - publish_clipboard
            filters: {}
          - actions:
            - read_node
            filters:
              published_file_type: Rendered Image
          - actions:
            - script_import
            filters:
              published_file_type: Nuke Script
          Task:
          - actions:
            - assign_task
            - task_to_ip
            filters: {}
          Version:
          - actions:
            - quicktime_clipboard
            - sequence_clipboard
            filters: {}
    bin_context_menu:
    - {app_instance: tk-multi-workfiles2, keep_in_menu: false, name: File Save...,
      requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot History...,
      requires_selection: true}
    - {app_instance: tk-multi-publish, keep_in_menu: false, name: Publish Project...,
      requires_selection: true}
    location:
      version: v0.6.11
      type: app_store
      name: tk-nuke
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    spreadsheet_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
    timeline_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
  #
  # -------------------------------------------------
  # Photoshop CC
  # -------------------------------------------------
  tk-photoshopcc:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    shelf_favorites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    - {app_instance: tk-multi-workfiles2, name: File Save...}
    location:
      version: v1.0.1
      type: app_store
      name: tk-photoshopcc
  #
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchhiero: '@launch_hiero'
      tk-multi-launchhoudini: '@launch_houdini'
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchnukestudio: '@launch_nukestudio'
      tk-multi-launchphotoshopcc: '@launch_photoshopcc'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
    location:
      version: v0.5.1
      type: app_store
      name: tk-shell
  #
  # -------------------------------------------------
  # Softimage
  # -------------------------------------------------
  tk-softimage:
    apps:
      tk-multi-about: '@about'
      tk-multi-shotgunpanel: '@shotgunpanel'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    location:
      version: v0.3.2
      type: app_store
      name: tk-softimage
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
#
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks:
  tk-framework-adminui_v0.x.x:
    location:
      version: v0.1.6
      type: app_store
      name: tk-framework-adminui
  tk-framework-softimageqt_v1.0.1:
    location:
      name: tk-framework-softimageqt
      type: app_store
      version: v1.0.1
