# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

################################################################################

includes:

# frameworks
- ./includes/common/frameworks.yml

# DCC-specific project environments
- ./includes/3dsmax/project.yml
- ./includes/desktop/project.yml
#- ./includes/flame/project.yml
- ./includes/hiero/project.yml
- ./includes/houdini/project.yml
#- ./includes/mari/project.yml
- ./includes/maya/project.yml
#- ./includes/motionbuilder/project.yml
- ./includes/nuke/project.yml
- ./includes/nukestudio/project.yml
- ./includes/photoshopcc/project.yml
- ./includes/shell/project.yml
- ./includes/shotgun/project.yml

################################################################################
# configuration for all engines to load in a project context

engines:
  tk-3dsmaxplus: "@3dsmax.project"
  tk-desktop: "@desktop.project"
  tk-hiero: "@hiero.project"
  tk-houdini: "@houdini.project"
  #tk-mari: "@mari.project"
  tk-maya: "@maya.project"
  #tk-motionbuilder: "@motionbuilder.project"
  tk-nuke: "@nuke.project"
  tk-nukestudio: "@nukestudio.project"
  tk-photoshopcc: "@photoshopcc.project"
  #tk-flame: "@flame.project"
  tk-shell: "@shell.project"
  tk-shotgun: "@shotgun.project"

################################################################################
# reference all of the common frameworks

frameworks: "@common.frameworks"
