# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml
- ./includes/common/apps.yml

- ./includes/houdini/project.yml
- ./includes/maya/project.yml
- ./includes/nuke/project.yml
- ./includes/photoshopcc/project.yml
- ./includes/shell/project.yml
- ./includes/3dsmax/project.yml

- ./includes/hiero/project.yml
- ./includes/mari/project.yml
- ./includes/motionbuilder/project.yml
- ./includes/nukestudio/project.yml
- ./includes/softimage/project.yml

#################################################################################################
# define all the items that should appear in this environment



engines:
  #
  # -------------------------------------------------
  # 3dsmax plus
  # -------------------------------------------------
  tk-3dsmaxplus: '@3dsmax.project'
  #
  # -------------------------------------------------
  # Shotgun Desktop
  # -------------------------------------------------
  tk-desktop:
    apps:
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-launchapp:
        use_software_entity: true
        location: "@common.apps.tk-multi-launchapp.location"
    groups:
    - matches: ['*Houdini*', '*Mari*', '*Max*', '*Maya*', '*Motion*', '*Nuke*', '*Photoshop*',
        '*Softimage*']
      name: Creative Tools
    - matches: ['*Hiero*']
      name: Editorial Tools
    - matches: ['*Fla*']
      name: Finishing Tools
    location:
      version: v2.3.0
      type: app_store
      name: tk-desktop
  #
  # -------------------------------------------------
  # Hiero
  # -------------------------------------------------
  tk-hiero: '@hiero.project'
  #
  # -------------------------------------------------
  # Houdini
  # -------------------------------------------------
  tk-houdini: '@houdini.project'
  #
  # -------------------------------------------------
  # Mari
  # -------------------------------------------------
  tk-mari: '@mari.project'
  #
  # -------------------------------------------------
  # Maya
  # -------------------------------------------------
  tk-maya: '@maya.project'
  #
  # -------------------------------------------------
  # Motionbuilder
  # -------------------------------------------------
  tk-motionbuilder: '@motionbuilder.project'
  #
  # -------------------------------------------------
  # Nuke
  # -------------------------------------------------
  tk-nuke: '@nuke.project'
  #
  # -------------------------------------------------
  # Nuke Studio
  # -------------------------------------------------
  tk-nukestudio: '@nukestudio.project'
  #
  # -------------------------------------------------
  # Photoshop CC
  # -------------------------------------------------
  tk-photoshopcc: '@photoshopcc.project'
  #
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell: '@shell.project'
  #
  # -------------------------------------------------
  # Softimage
  # -------------------------------------------------
  tk-softimage: '@softimage.project'
#
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks:
  tk-framework-adminui_v0.x.x:
    location:
      version: v0.1.6
      type: app_store
      name: tk-framework-adminui
  tk-framework-softimageqt_v1.0.1:
    location:
      name: tk-framework-softimageqt
      type: app_store
      version: v1.0.1
  tk-framework-desktopserver_v1.x.x:
    location:
      version: v1.1.10
      type: app_store
      name: tk-framework-desktopserver
