# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################
# include common definitions for all the launchers that are used to start maya, nuke etc.

includes: [./includes/app_launchers.yml, ./includes/common_apps.yml]


#################################################################################################
# define all the items that should appear in this environment

engines:

  tk-3dsmax:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    debug_logging: false
    location: {name: tk-3dsmax, type: app_store, version: v0.3.2}

  tk-3dsmaxplus:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    compatibility_dialog_min_version: 2016
    debug_logging: false
    menu_favourites: []
    location: {name: tk-3dsmaxplus, type: app_store, version: v0.1.5}

  tk-desktop:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchhiero: '@launch_hiero'
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
    collapse_rules:
    - {button_label: $app, match: Launch $app, menu_label: None}
    debug_logging: false
    default_group: Studio
    groups:
    - matches: ['*Hiero*', '*Houdini*', '*Mari*', '*Max*', '*Maya*', '*Motion*', '*Nuke*', '*Photoshop*', '*Softimage*']
      name: Creative Tools
    hook_launch_python: default
    location: {name: tk-desktop, type: app_store, version: v1.0.2}
    show_recents: true
    
  tk-hiero:
    apps:
      tk-hiero-export:
        custom_template_fields: []
        default_task_filter: '[[''step.Step.code'', ''is'', ''Comp'']]'
        default_task_template: Basic shot template
        hook_get_quicktime_settings: default
        hook_get_shot: default
        hook_resolve_custom_strings: default
        hook_translate_template: default
        hook_update_version_data: default
        hook_upload_thumbnail: default
        hook_get_extra_publish_data: default
        hook_pre_export: default
        location: {name: tk-hiero-export, type: app_store, version: v0.1.22}
        nuke_script_published_file_type: Nuke Script
        nuke_script_toolkit_write_nodes:
        - {channel: stereoexr32, name: 'Stereo Exr, 32 bit'}
        - {channel: stereoexr16, name: 'Stereo Exr, 16 bit'}
        - {channel: monodpx, name: Mono Dpx}
        plate_published_file_type: Hiero Plate
        audio_published_file_type: Hiero Audio
        template_nuke_script_path: nuke_shot_work
        template_plate_path: hiero_plate_path
        template_render_path: hiero_render_path
        template_version: hiero_version
      tk-hiero-openinshotgun:
        location: {name: tk-hiero-openinshotgun, type: app_store, version: v0.1.0}
      tk-multi-about: '@about'
      tk-multi-publish:
        allow_taskless_publishes: true
        display_name: Publish Project
        expand_single_items: false
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.6.2}
        primary_description: Publish and version up the selected Hiero project
        primary_display_name: Hiero Publish
        primary_icon: icons/publish_hiero_main.png
        primary_publish_template: hiero_project_publish
        primary_scene_item_type: work_file
        primary_tank_type: Hiero Project
        secondary_outputs: []
        template_work: hiero_project_work
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.4.0}
        template_snapshot: hiero_project_snapshot
        template_work: hiero_project_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.6.0}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: []
        task_extra_display_fields: []
        template_publish: hiero_project_publish
        template_publish_area: hiero_project_publish_area
        template_work: hiero_project_work
        template_work_area: hiero_project_work_area
    bin_context_menu:
    - {app_instance: tk-multi-workfiles, keep_in_menu: false, name: Shotgun Save As...,
      requires_selection: true}
    - {app_instance: tk-multi-workfiles, keep_in_menu: false, name: Version up Current
        Scene..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot History...,
      requires_selection: true}
    - {app_instance: tk-multi-publish, keep_in_menu: false, name: Publish Project...,
      requires_selection: true}
    debug_logging: false
    location: {name: tk-hiero, type: app_store, version: v0.2.4}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    spreadsheet_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
    timeline_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
      
  tk-mari:
    apps:
      tk-multi-about: '@about'
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.6.0}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Asset]
        task_extra_display_fields: []
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: false
    location: {name: tk-mari, type: app_store, version: v1.0.0}
    
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles-launch-at-startup'
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.4.2}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    use_sgtk_as_menu_name: false
    
  tk-motionbuilder:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    debug_logging: false
    location: {name: tk-motionbuilder, type: app_store, version: v0.3.0}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    use_sgtk_as_menu_name: false
    
  tk-nuke:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    compatibility_dialog_min_version: 10
    debug_logging: false
    favourite_directories: []
    location: {name: tk-nuke, type: app_store, version: v0.2.24}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
    
  tk-photoshop:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    debug_logging: false
    location: {name: tk-photoshop, type: app_store, version: v0.2.0}
    
  tk-shell:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchhiero: '@launch_hiero'
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-launchsoftimage: '@launch_softimage'
      tk-multi-screeningroom: '@launch_screeningroom'
    location: {name: tk-shell, type: app_store, version: v0.4.0}
    
  tk-softimage:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    debug_logging: false
    location: {name: tk-softimage, type: app_store, version: v0.3.0}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    
frameworks:
  tk-framework-adminui_v0.x.x:
    location: {name: tk-framework-adminui, type: app_store, version: v0.0.7}
  tk-framework-login_v1.x.x:
    location: {name: tk-framework-login, type: app_store, version: v1.0.2}
  tk-framework-softimageqt_v1.0.1:
    location: {name: tk-framework-softimageqt, type: app_store, version: v1.0.1}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.18:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.18}
  tk-framework-widget_v0.1.19:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.19}
